[package]
name = "compiler-tester"
version = "1.3.3"
authors = [
    "Oleksandr Zarudnyi <a.zarudnyy@matterlabs.dev>",
    "Anton Dyadyuk <a.dyadyuk@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "EraVM Compiler Integration Testing Framework"

[[bin]]
name = "compiler-tester"
path = "src/compiler_tester/main.rs"

[lib]
doctest = false

[dependencies]
structopt = { version = "0.3", default-features = false }
anyhow = "1.0"
colored = "2.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
md5 = "0.7"
hex = "0.4"
sha3 = "0.10"
ron = "0.8"
regex = "1.8"
glob = "0.3"
semver = { version = "1.0", features = ["serde"] }
itertools = "0.10"
once_cell = "1.17"
rayon = "1.7"
lazy_static = "1.4"
bincode = "1.3"

zkevm-assembly = { git = "https://github.com/matter-labs/era-zkEVM-assembly", branch = "v1.3.2" }
zkevm_opcode_defs = { git = "https://github.com/matter-labs/era-zkevm_opcode_defs", branch = "v1.3.2" }
zkevm_tester = { git = "https://github.com/matter-labs/era-zkevm_tester", branch = "v1.3.3" }

compiler-common = { git = "https://github.com/matter-labs/era-compiler-common", branch = "main" }
compiler-llvm-context = { git = "https://github.com/matter-labs/era-compiler-llvm-context", branch = "main" }
compiler-solidity = { git = "https://github.com/matter-labs/era-compiler-solidity", branch = "main" }
compiler-vyper = { git = "https://github.com/matter-labs/era-compiler-vyper", branch = "main" }

solidity-adapter = { path = "../solidity_adapter" }
benchmark-analyzer = { path = "../benchmark_analyzer" }

[dependencies.tokio]
version = "1.28"
default-features = false
features = ["rt-multi-thread"]

[dependencies.web3]
version = "0.19"
default-features = false
features = ["http-rustls-tls", "test", "signing"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking"]

[dependencies.inkwell]
git = "https://github.com/matter-labs-forks/inkwell"
branch = "llvm-15"
default-features = false
features = ["llvm15-0", "no-libffi-linking", "target-eravm"]
