[package]
name = "compiler-tester"
version = "1.3.1"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
    "Anton Dyadyuk <a.dyadyuk@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "zkEVM Compiler Integration Testing Framework"

[[bin]]
name = "compiler-tester"
path = "src/compiler_tester/main.rs"

[lib]
doctest = false

[dependencies]
structopt = { version = "0.3", default-features = false }
shell-words = "1.1"
anyhow = "1.0"
colored = "2.0"

serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serde_yaml = "0.9"
md5 = "0.7"
hex = "0.4"
sha3 = "0.10"
ron = "0.8"
regex = "1.7"
glob = "0.3"
semver = { version = "1.0", features = [ "serde" ] }
itertools = "0.10"
rayon = "1.6"
lazy_static = "1.4"
bincode = "1.3"
web3 = { version= "0.18.0", default-features = false, features = ["http-rustls-tls", "test", "signing"] }

zkevm-assembly = { git = "https://github.com/matter-labs/era-zkEVM-assembly", branch = "main" }
zkevm_opcode_defs = { git = "https://github.com/matter-labs/era-zkevm_opcode_defs", branch = "main" }
zkevm_tester = { git = "https://github.com/matter-labs/era-zkevm_tester", branch = "v1.3.1" }

compiler-common = { git = "https://github.com/matter-labs/era-compiler-common", rev = "a6c5b02e4f149f82f1c3821a6f258363308abd2a" }
compiler-llvm-context = { git = "https://github.com/matter-labs/era-compiler-llvm-context", rev = "a1e29ba41fc081ff67d967c11d5e110d38e5b1ac" }
compiler-solidity = { git = "https://github.com/matter-labs/era-compiler-solidity", tag = "v1.3.6" }
compiler-vyper = { git = "https://github.com/matter-labs/era-compiler-vyper", tag = "v1.3.3" }

solidity-adapter = { path = "../solidity_adapter" }
benchmark-analyzer = { path = "../benchmark_analyzer" }

[dependencies.tokio]
version = "1.25"
default-features = false
features = ["rt-multi-thread"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking"]

[dependencies.inkwell]
git = "https://github.com/matter-labs-forks/inkwell"
branch = "llvm-15"
default-features = false
features = ["llvm15-0", "no-libffi-linking", "target-syncvm"]
