[package]
name = "benchmark-analyzer"
version = "1.3.1"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "The zkEVM benchmarks analyzer"

[[bin]]
name = "benchmark-analyzer"
path = "src/benchmark_analyzer/main.rs"

[dependencies]
structopt = { version = "0.3", default-features = false }
anyhow = "1.0"
colored = "2.0"

serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
libmath = "0.2"
